# Pipeline Template to build MkDocs

parameters:
  # Python Version to use for building mkdocs-material
  - name: PythonVersion
    type: string
    default: '3.9'
  # will update Submodule of mkdocs-material if not set to false
  - name: update_submodule
    type: boolean
    default: true

steps:
  # update MkDocs-Material Submodule if not set to false
  - ${{ if eq(parameters.update_submodule, true) }}:
      - template: checkout_submodules.yml
        parameters:
          submodule: mkdocs-material

  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.PythonVersion }}'
    inputs:
      versionSpec: ${{ parameters.PythonVersion }}
      addToPath: true
      architecture: 'x64'

  - task: Bash@3
    displayName: 'Install MkDocs'
    inputs:
      targetType: 'inline'
      script: 'pip install -e mkdocs-material'

  - task: Bash@3
    displayName: 'Build mkdocs'
    inputs:
      targetType: 'inline'
      script: 'mkdocs build'
