# Pipeline Template to build MkDocs
parameters:
  - name: pythonVersion
    type: string
    default: $(pythonVersion)
  - name: site_dir
    type: string
    default: site
  - name: deploy
    type: boolean
    default: false

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.pythonVersion }}'
    inputs:
      versionSpec: '${{ parameters.pythonVersion }}'
      addToPath: true
      architecture: x64

  - script: pip install --upgrade pip wheel setuptools
    displayName: update tools

  - script: pip install -e src/mkdocs-material
    displayName: install MkDocs-Material

  - script: pip install -r src/requirements-mkdocs-material.txt
    displayName: install requirements

  - script: mkdocs build --site-dir ${{ parameters.site-dir }} --verbose
    displayName: build docs

  - ${{ if eq(parameters.deploy, 'true') }}:
      - script: mkdocs gh-deploy --force --site-dir ${{ parameters.site-dir }} --verbose
        displayName: deploy to GitHub-Pages
