parameters:
  - name: PYTHON_VERSION
    type: string
    default: '3.9'
  - name: publishBuildArtifact
    type: boolean
    default: false

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.PYTHON_VERSION }}'
    inputs:
      versionSpec: ${{ parameters.PYTHON_VERSION }}
      addToPath: true

  - script: |
      python -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install setup
      pip install -r requirements.txt
    workingDirectory: $(projectRoot)
    displayName: 'Install Requirements'

  - ${{ if eq( parameters.publishBuildArtifact, 'true') }}:

      - task: PublishPipelineArtifact@1
        # condition: and(eq(variables.isProduction, 'true'), succeeded())
        inputs:
          targetPath: $(projectRoot)
          # targetPath: $(System.DefaultWorkingDirectory)/bin/WebApp
          artifactName: WebApp

      # - task: ArchiveFiles@2
      #   displayName: 'Archive files'
      #   # condition: and(eq(variables.isProduction, 'true'), succeeded())
      #   inputs:
      #     rootFolderOrFile: $(projectRoot)
      #     includeRootFolder: false
      #     archiveType: zip
      #     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      #     replaceExistingArchive: true

      # - task: PublishBuildArtifacts@1
      #   displayName: Publish Build Artifact
      #   condition: and(eq(variables.isProduction, 'true'), succeeded())
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      #     ArtifactName: 'drop'
      #     publishLocation: 'Container'
