# Pipeline Template to build MkDocs

parameters:
  - name: PYTHON_VERSION
    type: string
    default: $(pythonVersion)

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.PYTHON_VERSION }}'
    inputs:
      versionSpec: '${{ parameters.PYTHON_VERSION }}'
      addToPath: true
      architecture: x64

  - script: pip install --upgrade pip wheel setuptools
    displayName: update tools

  - script: pip install -e src/mkdocs-material
    displayName: install MkDocs-Material

  - script: pip install -r src/requirements-mkdocs-material.txt
    displayName: install requirements

  - script: mkdocs build
    displayName: build docs
