# Pipeline Template to build MkDocs

parameters:
  # Python Version to use for building mkdocs-material
  - name: PYTHON_VERSION
    type: string
    default: $(pythonVersion)

steps:
  - template: checkout_submodules.yml
    parameters:
      submodule: src/mkdocs-material

  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.PYTHON_VERSION }}'
    inputs:
      versionSpec: ${{ parameters.PYTHON_VERSION }}
      addToPath: true
      architecture: 'x64'

  - task: Bash@3
    displayName: 'Install mkdocs-material'
    inputs:
      targetType: 'inline'
      script: |
        pip install --upgrade pip wheel setuptools
        pip install -e src/mkdocs-material
        pip install mkdocs-git-revision-date-plugin

  - task: Bash@3
    displayName: 'Build MkDocs'
    inputs:
      targetType: 'inline'
      script: 'mkdocs build'
