# Pipeline Template to update submodules
# Useful for bigger (Mono)-Repos where only a subset of submodules is necessary

parameters:
  # set to false to disable checkout self first
  - name: checkoutSelf
    type: boolean
    default: true
  # Submodule to update/init
  - name: submodule
    type: string
    default: ''
  # Update submodules recursive
  - name: recursive
    type: boolean
    default: false
  # Enable Debug Output to list content of submodule-directories before and after update
  - name: debug
    type: boolean
    default: false

steps:
  - ${{ if eq(parameters.checkoutSelf, true) }}:
      - checkout: self
        submodules: false
        displayName: Checkout self
        persistCredentials: true

  - ${{ if eq(parameters.debug, true) }}:
      - script: ls -la ${{ parameters.submodule }}
        displayName: ls ${{ parameters.submodule }}

  - ${{ if eq(parameters.recursive, false) }}:
      - script: git submodule update --init ${{ parameters.submodule }}
        displayName: 'update submodule ${{ parameters.submodule }}'

  - ${{ if eq(parameters.recursive, true) }}:
      - script: git submodule update --init --recursive ${{ parameters.submodule }}
        displayName: 'update submodule ${{ parameters.submodule }} recursive'

  - ${{ if eq(parameters.debug, true) }}:
      - script: ls -la ${{ parameters.submodule }}
        displayName: ls ${{ parameters.submodule }}
