steps:
  - template: python_django_export_projectroot.yml

  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ variables.pythonVersion }}
    displayName: Use Python ${{ variables.pythonVersion }}

  - task: AzurePowerShell@5
    name: readWebAppName
    displayName: Read WebApp Name
    retryCountOnTaskFailure: 3
    continueOnError: false
    inputs:
      azureSubscription: $(azureSubscription)
      ScriptType: InlineScript
      Inline: |
        $webAppName = ( Get-AzWebApp -ResourceGroupName $(resourceGroupName) ).Name
        Write-Host "##vso[task.setvariable variable=webAppName]$webAppName"
      azurePowerShellVersion: LatestVersion
      pwsh: true

  - task: AzureWebApp@1
    displayName: Deploy Azure Web App
    inputs:
      azureSubscription: $(azureSubscription)
      appType: webAppLinux
      appName: $(webAppName)
      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
      runtimeStack: PYTHON|3.9
      startUpCommand: python3.9 manage.py migrate
