steps:
  - task: AzureCLI@2
    name: DeployBicepFile
    displayName: Deploy Bicep file
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
          --name $(Build.BuildNumber) \
          --resource-group $(ResourceGroupName) \
          --template-file main.bicep \
          --parameters secretKey=$(secretKey)
    env:
      secretKey: $(secretKey)
