parameters:
  - name: resourceGroupName
    type: string
  - name: azureSubscription
    type: string

steps:
  - task: AzurePowerShell@5
    name: readWebAppName
    displayName: Read WebApp Name
    retryCountOnTaskFailure: 3
    continueOnError: false
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      ScriptType: InlineScript
      Inline: |
        $webAppName = ( Get-AzWebApp -ResourceGroupName ${{ parameters.resourceGroupName }} ).Name
        Write-Host "##vso[task.setvariable variable=webAppName]$webAppName"
      azurePowerShellVersion: LatestVersion
      pwsh: true
