steps:
  - task: ArchiveFiles@2
    displayName: 'Create Build Artifact'
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    inputs:
      rootFolderOrFile: '$(projectRoot)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
