## Search all subdirectories for 'manage.py' and create projectRoot variable

parameters:
  - name: 'PYTHON_VERSION'
    type: string
    default: '3.9'

steps:
  - template: checkout_submodules.yml
    parameters:
      submodule: django_webapp

  - task: UsePythonVersion@0
    displayName: Use Python version ${{ parameters.PYTHON_VERSION }}
    inputs:
      versionSpec: ${{ parameters.PYTHON_VERSION }}
      architecture: 'x64'

  - task: PythonScript@0
    displayName: 'Export project path'
    inputs:
      scriptSource: 'inline'
      script: |
        """Search all subdirectories for `manage.py`."""
        from glob import iglob
        from os import path
        # Python >= 3.5
        manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
        if not manage_py:
            raise SystemExit('Could not find a Django project')
        project_location = path.dirname(path.abspath(manage_py))
        print('Found Django project in', project_location)
        print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))
