# https://docs.microsoft.com/en-us/azure/devops/azure-pipelines/process/conditions?view=azure-devops&tabs=yaml#ive-got-a-conditional-step-that-runs-even-when-a-job-is-canceled-how-do-i-manage-to-cancel-all-jobs-at-once

stages:
  - stage: Stage1
    displayName: Stage 1
    dependsOn: []
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/main'), succeeded())
    jobs:
      - job: ShowVariables
        displayName: Show variables
        steps:
          - task: CmdLine@2
            displayName: Show variables
            inputs:
              script: 'printenv'

  - stage: Stage2
    displayName: stage 2
    dependsOn: Stage1
    condition: contains(variables['build.sourceBranch'], 'refs/heads/main')
    jobs:
      - job: ShowVariables
        displayName: Show variables 2
        steps:
          - task: CmdLine@2
            displayName: Show variables 2
            inputs:
              script: 'printenv'

  - stage: Stage3
    displayName: stage 3
    dependsOn: Stage2
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/main'), succeeded())
    jobs:
      - job: ShowVariables
        displayName: Show variables 3
        steps:
          - task: CmdLine@2
            displayName: Show variables 3
            inputs:
              script: 'printenv'
