variables:
  - name: foo
    value: contoso # triggers elseif condition

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "start"
  - ${{ if eq(variables.foo, 'adaptum') }}:
      - script: echo "this is adaptum"
  - ${{ elseif eq(variables.foo, 'contoso') }}: # true
      - script: echo "this is contoso"
  - ${{ else }}:
      - script: echo "the value is not adaptum or contoso"
