trigger:
  batch: true
  branches:
    include:
      - refs/heads/production
      - refs/heads/main
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  branches:
    include:
      - production
      - main

variables:
  - group: django_gh
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
    readonly: true
  - name: isProduction
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]
    readonly: true
  - name: isPullRequest
    value: $[eq(variables['Build.Reason'], 'PullRequest')]
    readonly: true
  - template: azure-pipelines/variables/main.yml

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Bicep
    dependsOn:
    jobs:
      - template: azure-pipelines/jobs/validate_bicep.yml
      - ${{ if eq(variables.isMain, 'True') }}:
          - deployment: DeployBicep
            displayName: Create Azure Resources
            environment: $(environmentName)
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: azure-pipelines/jobs/steps/deploy_bicep.yml

  - stage: Testing
    dependsOn: Bicep
    condition: in(dependencies.Bicep.result, 'Succeeded', 'Skipped')
    displayName: Run runTests
    variables:
      - group: django-dev
    jobs:
      - job: runTests
        displayName: run python tests
        steps:
          - template: azure-pipelines/jobs/steps/checkout_submodules.yml
            parameters:
              submodule: 'src/webapp'
          - template: azure-pipelines/jobs/steps/python_django_test.yml
            parameters:
              PYTHON_VERSIONS:
                - $(pythonVersion)

  - stage: WebApp
    dependsOn: Testing
    condition: in(dependencies.Testing.result, 'Succeeded')
    jobs:
      - template: azure-pipelines/jobs/build_webapp.yml
      - ${{ if eq(variables.isProduction, 'True') }}:
          - deployment: DeployDjango
            dependsOn: BuildWebApp
            displayName: Deploy Django to WebApp
            environment: $(environmentName)
            strategy:
              runOnce:
                deploy:
                  steps:
                    - template: azure-pipelines/jobs/steps/deploy_webapp.yml

  - stage: MkDocs
    displayName: MkDocs-Material
    dependsOn: WebApp
    # condition: in(dependencies.WebApp.result, 'Succeeded')
    jobs:
      - job:
        displayName: MkDocs-Material
        steps:
          - template: azure-pipelines/jobs/steps/checkout_submodules.yml
            parameters:
              submodule: 'src/mkdocs-material'
          - template: azure-pipelines/jobs/steps/build_mkdocs.yml
          - ${{ if eq(variables.isMain, 'True') }}:
              - template: azure-pipelines/jobs/steps/publish_mkdocs.yml
