trigger:
  branches:
    include:
      - refs/heads/stable
      - refs/heads/main
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  branches:
    include:
      - stable
      - main

variables:
  - group: django_gh
  - group: django-dev
  - group: django-superuser
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
  - name: pythonVersion
    value: '3.9'
  - name: resourceGroupName
    value: 'django_gh'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'django_gh'
  - name: vmImageName
    value: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job: MkDocs
        steps:
          - template: azure-pipelines/jobs/steps/build_mkdocs.yml
          - task: Bash@3
            displayName: Deploy to GitHub-Pages
            condition: and(eq(variables.isStable, 'true'), succeeded())
            inputs:
              targetType: 'inline'
              script: 'mkdocs gh-deploy --force --clean'

  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: azure-pipelines/jobs/validate_bicep.yml

  - stage: CreateResources
    displayName: Create Azure Resources
    dependsOn: ValidateBicep
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployBicep
        displayName: Create Azure Resources
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                # - checkout: self
                #   submodules: false
                - template: azure-pipelines/jobs/steps/deploy_bicep.yml

  - stage: WebApp
    dependsOn: CreateResources
    condition: in(dependencies.CreateResources.result, 'Succeeded', 'SucceededWithIssues', 'Skipped')
    displayName: WebApp
    jobs:
      - job: BuildWebApp
        displayName: Build Web App
        steps:
          - template: azure-pipelines/jobs/steps/python_django_export_projectroot.yml

          - template: azure-pipelines/jobs/steps/get_appinsights_con_str.yml
            parameters:
              azureSubscription: $(azureSubscription)
              resourceGroupName: $(resourceGroupName)

          - template: azure-pipelines/jobs/steps/build_webapp.yml
            parameters:
              PYTHON_VERSION: $(pythonVersion)

          - template: azure-pipelines/jobs/steps/publish_artifact.yml

      - deployment: DeployDjango
        dependsOn: BuildWebApp
        condition: and(succeeded() , eq(variables.isStable, 'true'))
        displayName: Deploy Django to WebApp
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-pipelines/jobs/steps/deploy_webapp.yml
