trigger:
  batch: true
  branches:
    include:
      - refs/heads/stable
      - refs/heads/main
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  branches:
    include:
      - stable
      - main

variables:
  - group: django_gh
  - name: isMain
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/main') ]
    readonly: true
  - name: isStable
    value: $[ eq(variables['Build.SourceBranch'], 'refs/heads/stable') ]
    readonly: true
  - name: isPullRequest
    value: $[ eq(variables['Build.Reason'], 'PullRequest') ]
    readonly: true
  - name: sourceBranchName
    value: $[ variables['Build.SourceBranchName'] ]
    readonly: true
  - template: azure-pipelines/variables/default.yml
  - ${{ if eq(variables.isMain, 'True') }}:
      - template: azure-pipelines/variables/main.yml
  - ${{ if eq(variables.isStable, 'True') }}:
      - template: azure-pipelines/variables/stable.yml

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Bicep
    dependsOn:
    variables:
      - group: django-dev
      - group: django-superuser
    jobs:
      - template: azure-pipelines/jobs/validate_bicep.yml
      - ${{ if eq(variables.sourceBranchName, 'main') }}:
          - job:
            variables:
              - group: django-dev
              - group: django-superuser
            steps:
              - task: AzureCLI@2
                name: DeployBicepFile
                displayName: Deploy Bicep file
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    az deployment group create \
                      --name $(Build.BuildNumber) \
                      --resource-group $(resourceGroupName) \
                      --template-file main.bicep \
                      --parameters secretKey=$(secretKey)
                env:
                  secretKey: $(secretKey)

  - stage: Testing
    dependsOn: Bicep
    displayName: Run runTests
    variables:
      - group: django-dev
    jobs:
      - job: runTests
        displayName: run python tests
        steps:
          - template: azure-pipelines/jobs/steps/checkout_submodules.yml
            parameters:
              submodule: 'src/webapp'
          - template: azure-pipelines/jobs/steps/python_django_test.yml
            parameters:
              pythonVersions:
                - '${{ variables.pythonVersion }}'

  - stage: WebApp
    dependsOn: Testing
    variables:
      - group: dhango-dev
      - group: django-superuser
    jobs:
      - template: azure-pipelines/jobs/build_webapp.yml
        parameters:
          pythonVersion: $(pythonVersion)
          resourceGroupName: $(resourceGroupName)
          azureSubscription: $(azureSubscription)
      - job:
        condition: eq(variables.sourceBranchName, 'main')
        steps:
          - template: azure-pipelines/jobs/steps/deploy_webapp.yml
            parameters:
              resourceGroupName: $(resourceGroupName)
              azureSubscription: $(azureSubscription)

  - stage: MkDocs
    dependsOn: WebApp
    jobs:
      - template: azure-pipelines/jobs/mkdocs-material.yml
        parameters:
          pythonVersion: $(pythonVersion)
          mkdocsSiteDir: $(mkdocsSiteDir)
          mkdocsDeploy: ${{ variables.mkdocsDeploy }}
