trigger:
  - stable

pr: none

variables:
  - group: django_gh
  - group: django-dev
  - group: django-superuser

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: pipelines/validate_bicep.yml

  - stage: CreateResources
    displayName: Create Azure Resources
    dependsOn: ValidateBicep
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployBicep
        displayName: Create Azure Resources
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  submodules: false
                - template: pipelines/deploy_bicep.yml

  - stage: BuildWebApp
    dependsOn: CreateResources
    condition: succeeded()
    displayName: 'Build and publish Artifact'
    jobs:
      - job: BuildWebApp
        displayName: 'Build Web App'
        steps:
          - checkout: self
            submodules: none
            persistCredentials: 'true'
          - script: 'git submodule update --init --recursive django_webapp'
            displayName: update django_webapp submodule
          - template: pipelines/build_webapp.yml
          - template: pipelines/run_tests.yml
          - template: pipelines/publish_artifact.yml

  - stage: DeployWebApp
    displayName: Deploy WebApp
    dependsOn: BuildWebApp
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployDjango
        displayName: 'Deploy Django to WebApp'
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipelines/deploy_webapp.yml
