trigger:
  branches:
    include:
      - refs/heads/stable
      - refs/heads/main
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

pr:
  branches:
    include:
      - stable
      - main

variables:
  - group: django_gh
  - group: django-dev
  - group: django-superuser
  - name: pythonVersion
    value: '3.9'
  - name: resourceGroupName
    value: 'django_gh'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'django_gh'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job:
        steps:
          - template: azure-pipelines/jobs/steps/build_mkdocs.yml
          - task: Bash@3
            displayName: 'Deploy to GitHub-Pages'
            condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
            inputs:
              targetType: 'inline'
              script: 'mkdocs gh-deploy --force --clean'

  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: azure-pipelines/jobs/validate_bicep.yml

  - stage: CreateResources
    displayName: Create Azure Resources
    dependsOn: ValidateBicep
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployBicep
        displayName: Create Azure Resources
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  submodules: false
                - template: azure-pipelines/jobs/steps/deploy_bicep.yml

  - stage: BuildWebApp
    dependsOn: CreateResources
    condition: succeeded()
    displayName: 'Build and publish Django'
    jobs:
      - job: BuildWebApp
        displayName: 'Build Web App'
        steps:
          - template: azure-pipelines/jobs/steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp

          - template: azure-pipelines/jobs/steps/get_appinsights_con_str.yml
            parameters:
              azureSubscription: $(azureSubscription)
              resourceGroupName: $(resourceGroupName)

          - template: azure-pipelines/jobs/steps/build_webapp.yml
            parameters:
              PYTHON_VERSION: $(pythonVersion)

          - template: azure-pipelines/jobs/steps/publish_artifact.yml

  - stage: DeployWebApp
    displayName: Deploy WebApp
    dependsOn: BuildWebApp
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployDjango
        displayName: 'Deploy Django to WebApp'
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-pipelines/jobs/steps/deploy_webapp.yml
