trigger:
  - stable
  - feature/*

pr: none

variables:
  - group: django_gh
  - group: django-dev
  - group: django-superuser

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: azure-pipelines/jobs/validate_bicep.yml

  - stage: CreateResources
    displayName: Create Azure Resources
    dependsOn: ValidateBicep
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployBicep
        displayName: Create Azure Resources
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  submodules: false
                - template: azure-pipelines/jobs/steps/deploy_bicep.yml

  - stage: BuildWebApp
    dependsOn: CreateResources
    condition: succeeded()
    displayName: 'Build and publish Artifact'
    jobs:
      - job: BuildWebApp
        displayName: 'Build Web App'
        steps:
          - template: azure-pipelines/jobs/steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp

          - template: azure-pipelines/jobs/steps/build_webapp.yml
            parameters:
              azureSubscription: django_gh
              resourceGroupName: django_gh
              projectRoot: $(System.DefaultWorkingDirectory)/django_webapp
              debug: false
          - template: azure-pipelines/jobs/steps/run_tests.yml
          - template: azure-pipelines/jobs/steps/publish_artifact.yml

  - stage: DeployWebApp
    displayName: Deploy WebApp
    dependsOn: BuildWebApp
    condition: and(contains(variables['build.sourceBranch'], 'refs/heads/stable'), succeeded())
    jobs:
      - deployment: DeployDjango
        displayName: 'Deploy Django to WebApp'
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: azure-pipelines/jobs/steps/deploy_webapp.yml
