pr:
  drafts: true
  autoCancel: false
  branches:
    exclude:
      - main
  paths:
    include:
      - django_webapp
      - pipelines
      - azure-pipelines.yml

variables:
  - group: django_gh
  - group: django-dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: validate_bicep.yml

  - stage: BuildWebApp
    dependsOn:
    displayName: Build Web App
    jobs:
      - job: BuildWebApp
        displayName: Build Web App
        variables:
          - group: django-superuser
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
          - template: build_webapp.yml

  - stage: RunTests
    dependsOn: BuildWebApp
    displayName: Run Tests
    jobs:
      - job: RunTests
        displayName: Run Unit Tests
        steps:
          - template: run_tests.yml
