pr:
  branches:
    exclude:
    - main

variables:
  # Azure Resource Group where the Resources will be deployed
  resourceGroupName: 'django-mauwiidev'
  # Location of the Resourcegroup
  location: 'westeurope'
  # ARM Service Connection
  azureSubscription: 'django-mauwii-arm'
  # Web app name
  webAppName: 'django-mauwiidevoqchu5wfujocm'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'django-oqchu5wfujocm'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: '$(System.DefaultWorkingDirectory)/django_webapp'
  # Python version: 3.9
  pythonVersion: 3.9

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: Bicep_Validation.yml

  - stage: BuildWebApp
    dependsOn:
    displayName: Build Web App
    jobs:
      - job: BuildWebApp
        displayName: Build Web App
        steps:
          - template: build_webapp.yml
