parameters:
  - name: pythonVersion
    type: string
  - name: mkdocsSiteDir
    type: string
  - name: mkdocsDeploy
    type: boolean
jobs:
  - job:
    displayName: MkDocs-Material
    steps:
      - template: steps/checkout_submodules.yml
        parameters:
          submodule: 'src/mkdocs-material'
      - template: steps/build_mkdocs.yml
        parameters:
          pythonVersion: '${{ parameters.pythonVersion }}'
          mkdocsSiteDir: '${{ parameters.mkdocsSiteDir }}'
          mkdocsDeploy: '${{ parameters.mkdocsDeploy }}'
