parameters:
  - name: pythonVersion
    type: string
    # default: ${{ variables['pythonVersion'] }}
  - name: mkdocsSiteDir
    type: string
    default: 'site'
  - name: mkdocsDeploy
    type: string
    default: 'False'

jobs:
  - job:
    displayName: MkDocs-Material
    steps:
      - template: steps/checkout_submodules.yml
        parameters:
          submodule: 'src/mkdocs-material'

      - template: steps/build_mkdocs.yml
        parameters:
          pythonVersion: '${{ parameters.pythonVersion }}'
          mkdocsSiteDir: '${{ parameters.mkdocsSiteDir }}'

      - ${{ if eq(parameters.mkdocsDeploy, 'True') }}:
          - script: mkdocs gh-deploy --force --site-dir ${{ parameters.mkdocsSiteDir }} --verbose
            displayName: deploy to GitHub-Pages
