variables:
  - name: pythonVersion
    value: '3.9'
    readonly: true
  - name: resourceGroupName
    value: 'django_gh'
    readonly: true
  - name: location
    value: 'westeurope'
    readonly: true
  - name: azureSubscription
    value: 'django_gh'
    readonly: true
  - name: vmImageName
    value: 'ubuntu-latest'
    readonly: true
  - name: publish_docs
    value: false
