parameters:
  - name: azureSubscription
  - name: resourceGroupName
  - name: projectRoot
  - name: pythonVersion
    default: '3.9'
  - name: debug
    type: boolean
    default: false

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.pythonVersion }}'
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      addToPath: true

  - ${{ if eq(parameters['debug'], true) }}:
      - script: |
          echo "Parameters:"
          echo "azureSubscription: " $(parameters.azureSubscription)
          echo "resourceGroupName: " $(parameters.resourceGroupName)
          echo "projectRoot: " $(parameters.projectRoot) \n
          echo "With 'set':" \n
          set
          echo \n "With 'env':" \n
          env
        displayName: script env
        env:
          SECRET_KEY: ${{ variables.secretKey }}
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ variables.connectionString }}
          DJANGO_SUPERUSER_EMAIL: ${{ variables.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_PASSWORD: ${{ variables.DJANGO_SUPERUSER_PASSWORD }}

      - task: PythonScript@0
        continueOnError: true
        displayName: Python environ
        inputs:
          script: |
            import sys
            import os
            print(os.environ)
          workingDirectory: ${{ variables.projectRoot }}
          pythonInterpreter: '/antenv/bin/python'
          scriptSource: inline
        env:
          SECRET_KEY: ${{ variables.secretKey }}
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ variables.connectionString }}
          DJANGO_SUPERUSER_EMAIL: ${{ variables.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SUPERUSER_PASSWORD: ${{ variables.DJANGO_SUPERUSER_PASSWORD }}

  - task: AzurePowerShell@5
    displayName: 'Read Connection String'
    name: readAppInsights
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      ScriptType: 'InlineScript'
      Inline: |
        $appInsightResource = Get-AzApplicationInsights -ResourceGroupName "${{ parameters.resourceGroupName }}"
        $APPLICATIONINSIGHTS_CONNECTION_STRING = $appInsightResource.ConnectionString
        Write-Host "##vso[task.setvariable variable=connectionString;issecret=true]$APPLICATIONINSIGHTS_CONNECTION_STRING"
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true

  - script: |
      python3 -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install -r requirements.txt
    workingDirectory: ${{ variables.projectRoot }}
    displayName: 'Create antenv'
    env:
      SECRET_KEY: ${{ variables.secretKey }}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ variables.connectionString }}
      DJANGO_SUPERUSER_EMAIL: ${{ variables.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ variables.DJANGO_SUPERUSER_PASSWORD }}

  - script: |
      python manage.py migrate
      python manage.py createsuperuser --noinput
    workingDirectory: ${{ variables.projectRoot }}
    displayName: 'Create antenv'
    env:
      SECRET_KEY: ${{ variables.secretKey }}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ variables.connectionString }}
      DJANGO_SUPERUSER_EMAIL: ${{ variables.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ variables.DJANGO_SUPERUSER_PASSWORD }}

  - task: PythonScript@0
    continueOnError: true
    displayName: Run Tests
    inputs:
      scriptSource: filePath
      scriptPath: manage.py
      arguments: test
      workingDirectory: ${{ variables.projectRoot }}
      pythonInterpreter: 'antenv/bin/python'
    env:
      SECRET_KEY: ${{ variables.secretKey }}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ variables.connectionString }}
      DJANGO_SUPERUSER_EMAIL: ${{ variables.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ variables.DJANGO_SUPERUSER_PASSWORD }}
