parameters:
  - name: azureSubscription
  - name: resourceGroupName
  - name: pythonVersion
    default: '3.9'
  - name: projectRoot
    default: $(Build.SourcesDirectory)
  - name: debug
    type: boolean
    default: false

steps:
  - task: AzurePowerShell@5
    displayName: 'Read Connection String'
    name: readAppInsights
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      ScriptType: 'InlineScript'
      Inline: |
        $appInsightResource = Get-AzApplicationInsights -ResourceGroupName "${{ parameters.resourceGroupName }}"
        $APPLICATIONINSIGHTS_CONNECTION_STRING = $appInsightResource.ConnectionString
        Write-Host "##vso[task.setvariable variable=connectionString;issecret=true]$APPLICATIONINSIGHTS_CONNECTION_STRING"
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true

  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.pythonVersion }}'
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}

  - script: |
      python3 -m venv antenv
      source antenv/bin/activate
    workingDirectory: ${{ parameters.projectRoot }}
    displayName: 'Create antenv'

  - script: |
      source antenv/bin/activate
      python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
    workingDirectory: ${{ parameters.projectRoot }}

  - script: |
      source antenv/bin/activate
      antenv/bin/python -m pip install -r requirements.txt
    workingDirectory: ${{ parameters.projectRoot }}
    displayName: 'Install requirements'

  - ${{ if eq(parameters.debug, true) }}:
      - script: set
        displayName: Show Variables
        env:
          SECRET_KEY: $(secretKey)
          APPLICATIONINSIGHTS_CONNECTION_STRING: $(connectionString)
          DJANGO_SUPERUSER_EMAIL: $(DJANGO_SUPERUSER_EMAIL)
          DJANGO_SUPERUSER_PASSWORD: $(DJANGO_SUPERUSER_PASSWORD)
          TESTVALUE: foo

      - task: PythonScript@0
        continueOnError: true
        displayName: Python print environ
        env:
          SECRET_KEY: $(secretKey)
          APPLICATIONINSIGHTS_CONNECTION_STRING: $(connectionString)
          DJANGO_SUPERUSER_EMAIL: $(DJANGO_SUPERUSER_EMAIL)
          DJANGO_SUPERUSER_PASSWORD: $(DJANGO_SUPERUSER_PASSWORD)
        inputs:
          workingDirectory: ${{ parameters.projectRoot }}
          pythonInterpreter: '${{ parameters.projectRoot }}/antenv/bin/python'
          scriptSource: inline
          script: |
            import sys
            import os
            print(os.environ)

  - script: |
      source antenv/bin/activate
      export SECRET_KEY="$(secretKey)"
      export APPLICATIONINSIGHTS_CONNECTION_STRING="$(connectionString)"
      antenv/bin/python manage.py makemigrations
    workingDirectory: ${{ parameters.projectRoot }}
    displayName: 'Make Migrations'
    env:
      SECRET_KEY: '$(secretKey)'
      APPLICATIONINSIGHTS_CONNECTION_STRING: $(connectionString)

  - script: |
      source antenv/bin/activate
      export SECRET_KEY="$(secretKey)"
      export APPLICATIONINSIGHTS_CONNECTION_STRING="$(connectionString)"
      antenv/bin/python manage.py migrate
    workingDirectory: ${{ parameters.projectRoot }}
    displayName: 'Migrate'
    env:
      SECRET_KEY: '$(secretKey)'
      APPLICATIONINSIGHTS_CONNECTION_STRING: $(connectionString)

  - script: |
      export SECRET_KEY=$(secretKey)
      export APPLICATIONINSIGHTS_CONNECTION_STRING="$(connectionString)"
      export DJANGO_SUPERUSER_USERNAME="$(DJANGO_SUPERUSER_USERNAME)"
      export DJANGO_SUPERUSER_EMAIL="$(DJANGO_SUPERUSER_EMAIL)"
      export DJANGO_SUPERUSER_PASSWORD="$(DJANGO_SUPERUSER_PASSWORD)"
      source antenv/bin/activate
      antenv/bin/python manage.py createsuperuser --noinput
    displayName: 'Create Superuser'
    workingDirectory: ${{ parameters.projectRoot }}
    env:
      SECRET_KEY: $(secretKey)
      APPLICATIONINSIGHTS_CONNECTION_STRING: $(connectionString)
      DJANGO_SUPERUSER_EMAIL: $(DJANGO_SUPERUSER_EMAIL)
      DJANGO_SUPERUSER_PASSWORD: $(DJANGO_SUPERUSER_PASSWORD)
