# pipeline to test if things would work

trigger:
  - feature/experimental/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job: BuildDocs
        displayName: Build MkDocs
        dependsOn:

        steps:
          - template: steps/build_mkdocs.yml
            parameters:
              update_submodule: true

  - stage: Django
    dependsOn:
    jobs:
      - job: BuildDjango
        displayName: Build Django
        dependsOn:
        variables:
          - group: django_gh
          - group: django-dev
          - group: django-superuser

        steps:
          - template: steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp

          - template: steps/build_webapp.yml
            parameters:
              azureSubscription: django_gh
              resourceGroupName: django_gh
              projectRoot: $(System.DefaultWorkingDirectory)/django_webapp
              debug: false
