# pipeline to test if things would work

trigger:
  - feature/experimental/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job: ExperimentalCheckoutDocs
        displayName: Test new Steps
        dependsOn:
        steps:
          - template: steps/checkout_submodules.yml
            parameters:
              submodule: mkdocs-material
      - job: BuildDocs
        displayName: Build MkDocs
        dependsOn: ExperimentalCheckoutDocs
        steps:
          - template: steps/build_mkdocs.yml
            parameters:
              update_submodule: false

  - stage: Django
    dependsOn:
    jobs:
      - job: ExperimentalCheckoutDjango
        displayName: Test new Steps
        dependsOn:
        steps:
          - template: steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp
      - job: ExperimentalBuildDjango
        displayName: Build Experimental
        dependsOn: ExperimentalCheckoutDjango
        variables:
          - group: django_gh
          - group: django-dev
          - group: django-superuser
        steps:
          - template: steps/build_webapp.yml
            parameters:
              azureSubscription: django_gh
              resourceGroupName: django_gh
              projectRoot: $(System.DefaultWorkingDirectory)/django_webapp
              debug: false
