# pipeline to test if things would work

trigger:
  branches:
    include:
      - feature/experimental/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: django_gh
  - name: pythonVersion
    value: '3.9'
  - name: resourceGroupName
    value: 'django_gh'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'django_gh'
  - name: isPullRequest
    value: $[eq(variables['Build.Reason'], 'PullRequest')]
    readonly: True
  - name: sourceBranchName
    value: $[variables['Build.SourceBranchName']]
    readonly: True
  - name: destinationBranchName
    value: $[variables['System.PullRequest.TargetBranch']]
    readonly: True

stages:
  - stage: validateBranch
    dependsOn:
    displayName: Validate Branch
    jobs:
      - job: noPullRequest
        condition: eq(variables.isPullRequest, 'False')
        steps:
          - script: 'env'

  - stage: pulumi
    dependsOn:
    jobs:
      - job:
        variables:
          - group: pulumi
        steps:
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodule: 'src/pulumi'
          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
              architecture: x64
          - task: AzureCLI@2
            env:
              PULUMI_ACCESS_TOKEN: '$(pulumi)'
            inputs:
              azureSubscription: Mauwii
              scriptType: pscore
              workingDirectory: src/quickstart
              inlineScript: |
                ls -la
                python3 -m venv venv
                source venv/bin/activate
                brew install pulumi
                pulumi about
                pulumi config set azure-native:location westeurope
  # - stage: MkDocs
  #   dependsOn:
  #   jobs:
  #     - job: BuildDocs
  #       displayName: 'Build MkDocs'
  #       dependsOn:
  #       steps:
  #         - template: jobs/steps/build_mkdocs.yml
  #           parameters:
  #             update_submodule: true

  # - stage: Experimental_Django
  #   dependsOn:
  #   jobs:
  #     - job: BuildDjango
  #       displayName: 'Build Django'
  #       dependsOn:
  #       variables:
  #         - group: django-dev
  #         - group: django-superuser
  #       steps:
  #         - template: jobs/steps/checkout_submodules.yml
  #           parameters:
  #             submodule: 'src/webapp'
  #             # checkoutSelf: false
  #             # recursive: false
  #             # debug: true
  #         - template: jobs/steps/get_appinsights_con_str.yml
  #           parameters:
  #             azureSubscription: $(azureSubscription)
  #             resourceGroupName: $(resourceGroupName)
  #         - template: jobs/steps/build_webapp_experimental.yml
  #           parameters:
  #             pythonVersion: $(pythonVersion)
  #             debug: true

  # - stage: Experimental_Django_Test
  #   dependsOn:
  #   jobs:
  #     - job: Run_Tests
  #       displayName: Python Tests
  #       dependsOn:
  #       variables:
  #         - group: django-dev
  #       steps:
  #         - template: jobs/steps/checkout_submodules.yml
  #           parameters:
  #             submodule: 'src/webapp'

  #         - template: jobs/steps/python_django_test_experimental.yml
  #           parameters:
  #             PYTHON_VERSIONS:
  #               - '3.10'
  #               - '3.9'
  #               - '3.8'
  #               - '3.7'
