# pipeline to test if things would work

trigger:
  batch: true
  branches:
    include:
      - feature/experimental/*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job: BuildDocs
        displayName: Build MkDocs
        dependsOn:

        steps:
          - template: jobs/steps/build_mkdocs.yml
            parameters:
              update_submodule: true

  - stage: Experimental_Django
    dependsOn:
    jobs:
      - job: BuildDjango
        displayName: Build Django
        dependsOn:
        variables:
          - group: django_gh
          - group: django-dev
          - group: django-superuser

        steps:
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp
              checkoutSelf: false
              recursive: false
              debug: true

          - template: jobs/steps/build_webapp_experimental.yml
            parameters:
              azureSubscription: 'django_gh'
              resourceGroupName: 'django_gh'
              projectRoot: '$(System.DefaultWorkingDirectory)/django_webapp'
              pythonVersion: '3.9'
              debug: false
