# pipeline to test if things would work

trigger:
  branches:
    include:
      - feature/experimental/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: django_gh
  - name: pythonVersion
    value: '3.9'
  - name: resourceGroupName
    value: 'django_gh'
  - name: location
    value: 'westeurope'
  - name: azureSubscription
    value: 'django_gh'

stages:
  - stage: MkDocs
    dependsOn:
    jobs:
      - job: BuildDocs
        displayName: 'Build MkDocs'
        dependsOn:
        steps:
          - template: jobs/steps/build_mkdocs.yml
            parameters:
              update_submodule: true

  - stage: Experimental_Django
    dependsOn:
    jobs:
      - job: BuildDjango
        displayName: 'Build Django'
        dependsOn:
        variables:
          - group: django-dev
          - group: django-superuser
        steps:
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp
              # checkoutSelf: false
              # recursive: false
              # debug: true
          - template: jobs/steps/get_appinsights_con_str.yml
            parameters:
              azureSubscription: $[ variables.azureSubscription ]
              resourceGroupName: $[ variables.resourceGroup ]
          - template: jobs/steps/build_webapp_experimental.yml
            parameters:
              pythonVersion: $[ variables.pythonVersion ]
              debug: true

  - stage: Experimental_Django_Test
    dependsOn:
    jobs:
      - job: Run_Tests
        displayName: Python Tests
        dependsOn:
        variables:
          - group: django-dev
        steps:
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodule: django_webapp

          - template: jobs/steps/python_django_test_experimental.yml
            parameters:
              PYTHON_VERSIONS:
                - '3.10'
                - '3.9'
                - '3.8'
                - '3.7'
