# only publishing Docs of stable release for now - maybe I integrate 'mike' later
trigger:
  - stable

# don't trigger for pull requests
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: submodules
    value: mkdocs-material

steps:
  # update MkDocs-Material Submodule
  - template: jobs/steps/checkout_submodules.yml
    parameters:
      submodules:
        - mkdocs-material

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.9.x'
    inputs:
      versionSpec: '3.9'
      addToPath: true
      architecture: 'x64'

  - task: Bash@3
    displayName: 'Install MkDocs'
    inputs:
      targetType: 'inline'
      script: 'pip install -e mkdocs-material'

  - task: Bash@3
    displayName: 'Build mkdocs'
    inputs:
      targetType: 'inline'
      script: 'mkdocs build'

  - task: Bash@3
    displayName: 'Deploy to GitHub-Pages'
    inputs:
      targetType: 'inline'
      script: 'mkdocs gh-deploy --force --clean'
