trigger:
  - main

pr:
  autoCancel: false
  branches:
    include:
      - main
      - feature/*
      - issue/*
    exclude:
      - feature/experimental/*

variables:
  - group: django_gh
  - group: django-dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ValidateBicep
    dependsOn:
    displayName: Bicep Validation
    jobs:
      - template: jobs/validate_bicep.yml

  - stage: BuildWebApp
    dependsOn:
    displayName: Build and Test

    jobs:
      - job: BuildWebApp
        displayName: Build Django
        variables:
          - group: django-superuser

        steps:
          - template: jobs/steps/checkout_submodules.yml
            parameters:
              submodules:
                - django_webapp

          - template: jobs/steps/build_webapp.yml
            parameters:
              azureSubscription: django_gh
              resourceGroupName: django_gh
              projectRoot: $(System.DefaultWorkingDirectory)/django_webapp
              debug: false

          - template: jobs/steps/run_tests.yml
